# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69a65c6cdd7aadb9fbbdab726202f10e1b1a2fd08b982a6fa99b24bc4854f19173372321cfd7f73e9ae2de1f6666661bd8deb481aba2c8b64c46bb79dbaac59

test:
  secret_key_base: cb234635a15cef469cd6486cf75c7243f00fdff9c15de141c87d06a89870edc7ea0ef95a4fc50dc2df20b1e7ac29bf39c192bfcd03671e564823169863b2ae4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
